//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PurchaseToProduct = new HashSet<PurchaseToProduct>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Descr { get; set; }
        public int Price { get; set; }
        public int Stock { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<PurchaseToProduct> PurchaseToProduct { get; set; }
    }
}
